services:
  apigateway:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: apigateway
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    external: false
