services:
  apigateway:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: apigateway
    ports:
      - "8080:8080"
    networks:
      - horizon-net
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      # Add any other environment variables your API gateway needs
      SPRING_PROFILES_ACTIVE: prod

networks:
  horizon-net:
    external: true
