server:
  port: 8084

spring:
  application:
    name: rsvp-service
  datasource:
    url: jdbc:mysql://localhost:3306/rsvpdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

spring:
  cloud:
    config:
      uri: http://localhost:8888 