apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventservice-deployment
  labels:
    app: eventservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventservice
  template:
    metadata:
      labels:
        app: eventservice
    spec:
      containers:
        - name: mysql
          image: mysql:9.3.0
          ports:
            - containerPort: 3306
