apiVersion: v1
kind: Service
metadata:
  name: eventservice-service
spec:
  selector:
    app: eventservice
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082
  type: NodePort
  