apiVersion: v1
kind: Service
metadata:
  name: mysql-eventservice
spec:
  selector:
    app: mysql-eventservice
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: NodePort
  