apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-eventservice-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: mysql:9.3.0
          ports:
            - containerPort: 80
