services:
  mysql-rsvp:
    image: mysql:8.0
    container_name: mysql-rsvp
    environment:
      - MYSQL_ROOT_PASSWORD=superSecret
      - MYSQL_DATABASE=rsvpservice_db
    ports:
      - "3309:3306"
    volumes:
      - rsvp-db-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - horizon-net

  rsvpservice:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: rsvpservice
    ports:
      - "8084:8084"
    networks:
      - horizon-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-rsvp:3306/rsvpservice_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: superSecret
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      mysql-rsvp:
        condition: service_healthy

volumes:
  rsvp-db-volume: {}

networks:
  horizon-net:
    external: true 