version: '3.8'

services:
  rsvp-service:
    build: .
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://rsvp-db:3306/rsvpdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - rsvp-db

  rsvp-db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=rsvpdb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - rsvp-db-data:/var/lib/mysql

volumes:
  rsvp-db-data: 