global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'userservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['userservice:8081']

  - job_name: 'eventservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']

  - job_name: 'notificationservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']
