global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'userservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['userservice-service:8081']

  - job_name: 'eventservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eventservice-service:8082']

  - job_name: 'rsvpservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rsvpservice-service:8084']

  - job_name: 'apigateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'apigateway-service:8080' ]
