global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'userservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['userservice:8081']

  - job_name: 'eventservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['eventservice:8082']

  - job_name: 'rsvpservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rsvpservice:8084']

  - job_name: 'apigateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'apigateway:8080' ]
