services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    ports:
      - "8083:8080"       # op deze manier staat keycloak op poort 8080 BINNEN de container 8083, keycloak staat standaard op 8080 namelijk
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
        - horizon-net
volumes:
  keycloak_data:


networks:
  horizon-net:
    external: true
