# keycloak/docker-compose.yml

services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/caettus/horizon-backend/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    ports:
      - "8083:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - horizon-net

volumes:
  keycloak_data:

networks:
  horizon-net:
    external: true
