version: '3.8'

services:
  keycloak:
    image: horizon-keycloak:latest
    ports:
      - "8083:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - horizon-net

volumes:
  keycloak_data:

networks:
  horizon-net:
    external: true
