apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi              # tweak size as needed
  storageClassName: standard   # works out-of-the-box on Minikube
