apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8083          # inside the cluster
      targetPort: 8083
      nodePort: 30083
  type: NodePort
