apiVersion: v1
kind: Secret
metadata:
  name: mysql-userservice-secret
type: Opaque
data:
  mysql-userservice-username: cm9vdA== # base64 encoded "root"
  mysql-userservice-password: c3VwZXJTZWNyZXQ= # base64 encoded "superSecret" 