services:
  mysql-event:
    image: mysql:8.0
    container_name: mysql-event
    environment:
      - MYSQL_ROOT_PASSWORD=superSecret
      - MYSQL_DATABASE=eventservice_db
    ports:
      - "3308:3306"  # extern 3308 -> intern 3306
    volumes:
      - event-db-volume:/var/lib/mysql

  eventservice:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: eventservice
    ports:
      - "8082:8080"  # Verander dit zodat het niet botst met userservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-event:3306/eventservice_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: superSecret
    depends_on:
      - mysql-event

volumes:
  event-db-volume:
