services:
  mysql-event:
    image: mysql:8.0
    container_name: mysql-event
    environment:
      - MYSQL_ROOT_PASSWORD=superSecret
      - MYSQL_DATABASE=eventservice_db
    ports:
      - "3308:3306"
    volumes:
      - my-db-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - horizon-net

  eventservice:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: eventservice
    ports:
      - "8082:8082"
    networks:
      - horizon-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-event:3306/eventservice_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: superSecret
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest

    depends_on:
      mysql-event:
        condition: service_healthy

volumes:
  my-db-volume: {}

networks:
  horizon-net:
    external: true
