apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: eventservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eventservice-deployment
  minReplicas: 1
  maxReplicas: 5 # Schaal tot maximaal 5 pods
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # Schaal op als gemiddeld CPU-gebruik over alle pods > 50% is