apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventservice-deployment
  labels:
    app: eventservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventservice
  template:
    metadata:
      labels:
        app: eventservice
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8082"
    spec:
      containers:
        - name: eventservice
          image: ghcr.io/caettus/horizon-backend/eventservice:latest
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: "250m" # 0.25 CPU core
              memory: "256Mi" # 256 MB geheugen
            limits:
              cpu: "500m" # Limiteer tot 0.5 CPU core
              memory: "512Mi" # Limiteer tot 512 MB geheugen
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-eventservice-config
                  key: mysql-url
            - name: SPRING_DATASOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-eventservice-secret
                  key: mysql-eventservice-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-eventservice-secret
                  key: mysql-eventservice-password
            - name: SPRING_SECURITY_USER_NAME
              value: "user"
            - name: SPRING_SECURITY_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eventservice-security-user-secret
                  key: password
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
              value: "DEBUG"
            - name: SPRING_RABBITMQ_HOST
              value: "eventbus-service"
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: eventbus-secret
                  key: rabbitmq-user
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eventbus-secret
                  key: rabbitmq-password
