apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      initContainers:
        - name: wait-for-mysql
          image: busybox:1.28
          command: [ 'sh', '-c', 'until nslookup mysql-keycloak && nc -z mysql-keycloak 3306; do echo waiting for mysql; sleep 2; done;' ]
      containers:
        - name: keycloak
          image: ghcr.io/caettus/horizon-backend/keycloak:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m" # 50% of a core
            limits:
              memory: "1Gi"
              cpu: "1" # 1 full core
          ports:
            - containerPort: 8080
          env:
            # Database Configuration
            - name: KC_DB
              value: "mysql"
            - name: KC_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-keycloak-config
                  key: mysql-url
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-keycloak-secret
                  key: mysql-keycloak-username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-keycloak-secret
                  key: mysql-keycloak-password

            # Admin User
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-secret
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-secret
                  key: KEYCLOAK_ADMIN_PASSWORD

            # Hostname Configuration
            - name: KC_HOSTNAME_PROVIDER
              value: "fixed"
            - name: KC_HOSTNAME
              value: "http://keycloak.132.164.221.89.nip.io"
            - name: KC_HOSTNAME_FRONTEND_URL
              value: "http://keycloak.132.164.221.89.nip.io"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_STRICT_HTTPS
              value: "false"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME_BACKCHANNEL
              value: "http://keycloak-service:8083"
            - name: KC_HOSTNAME_BACKCHANNEL_STRICT
              value: "false"
            - name: KC_HOSTNAME_BACKCHANNEL_DYNAMIC
              value: "true"
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-data-pvc