apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.2
          args: ["start-dev"]
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-secret
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-secret
                  key: KEYCLOAK_ADMIN_PASSWORD

              # Vertel Keycloak welke hostname provider te gebruiken
            - name: KC_HOSTNAME_PROVIDER
              value: "fixed"

            # De URL die als ISSUER in de tokens moet komen.
            # Dit is de interne service URL die je API Gateway verwacht.
            - name: KC_HOSTNAME_URL
              value: "http://keycloak.horizon.local/auth" # Base path, Keycloak voegt /realms/... toe.

            # De publiek toegankelijke URL voor de frontend (browser) interacties.
            # Gebruik hier de VASTE NodePort URL.
            - name: KC_HOSTNAME_FRONTEND_URL # Deze variabele zou de login/redirects moeten sturen.
              value: "http://keycloak.horizon.local/auth" # VERVANG <MINIKUBE_IP> met de output van 'minikube ip'

            # Optioneel: Als je de admin console via een specifieke (externe) URL wilt benaderen
            - name: KC_HOSTNAME_ADMIN_URL
              value: "http://keycloak.horizon.local/auth" # VERVANG <MINIKUBE_IP>

            - name: KC_HTTP_ENABLED # Zeker stellen dat HTTP werkt
              value: "true"
            - name: KC_PROXY
              value: "edge" # Kan helpen als Keycloak achter een proxy (zoals K8s service/NodePort) draait
            - name: KC_HOSTNAME_STRICT
              value: "false" # Maakt Keycloak minder streng over de Host header, nuttig voor dev


          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-data-pvc