apiVersion: v1
kind: Service
metadata:
  name: mysql-userservice
spec:
  selector:
    app: mysql-userservice
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP # Changed from NodePort to ClusterIP for internal DB service 