apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-eventservice-deployment
  labels:
    app: mysql-eventservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-eventservice
  template:
    metadata:
      labels:
        app: mysql-eventservice
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: mysql
          image: mysql:8.0
          readinessProbe:
            exec:
              command: [ "mysqladmin", "ping", "-h", "localhost" ]
            initialDelaySeconds: 10
            periodSeconds: 5
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-eventservice-secret
                  key: mysql-eventservice-password
            - name: MYSQL_DATABASE
              value: eventservice_db