apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  selector:
    app: node-exporter
  ports:
  - name: http
    port: 9100
    protocol: TCP
    targetPort: 9100 