apiVersion: v1
kind: Service
metadata:
  name: rsvpservice-service
spec:
  selector:
    app: rsvpservice
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30084
  type: NodePort 