apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
  labels:
    app: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8081"
    spec:
      containers:
        - name: userservice
          image: ghcr.io/caettus/horizon-backend/userservice:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-userservice-config
                  key: mysql-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-userservice-secret
                  key: mysql-userservice-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-userservice-secret
                  key: mysql-userservice-password
            - name: SPRING_RABBITMQ_HOST
              value: "eventbus-service" # Updated to use the k8s service name for eventbus
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom: # Fetching username from secret
                secretKeyRef:
                  name: eventbus-secret
                  key: rabbitmq-user
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom: # Fetching password from secret
                secretKeyRef:
                  name: eventbus-secret
                  key: rabbitmq-password
            - name: SPRING_SECURITY_USER_NAME
              value: "root"
            - name: SPRING_SECURITY_USER_PASSWORD
              value: "superSecret"
      imagePullSecrets:
        - name: ghcr-secret