services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=superSecret
      - MYSQL_DATABASE=userservice_db
    ports:
      - "3307:3306"
    volumes:
      - my-db-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  userservice:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: userservice
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/userservice_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: superSecret
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  my-db-volume: {}  # <-- Dit is wat ontbrak!
